### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/re2fa-converter#4]
In the spirit of getting more contributors to the project, the above documents would be appreciated.

**Comment by bislara** [comment]
I would also like to contribute to this. Can you please assign it to me?

**Comment by gridhead** [comment]
Cool. I will assign you this issue. Be sure to get yourself registered at https://organize.mlh.io/participants/events/4659-hack-astrosonic, our official Hacktoberfest event to stay in touch with the fellow contributors of this project.

Also, feel free to leave a star on the project - should you find it worth your time. Happy hacking! :smile:

**Comment by bislara** [comment]
Thanks, I will create a PR on 1st October ✌

**Comment by gridhead** [comment]
Resolved #4 via #8.
